name: RSpec

on:
  push:
  pull_request:

jobs:
  rspec:
    name: Run RSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Bundle Install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true

      - name: Run RSpec
        run: bundle exec rspec
